name: Build and publish
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base '/collaborative-programming-github/'

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist



  prepare_website:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Download documents
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: List artifacts
        run: ls -R
        working-directory: artifacts

      - name: Move to deploy directory
        run: |
          mv dist/ deploy/
      - name: List documents
        run: ls -R
        working-directory: deploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: deploy/

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: prepare_website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
